name: Dev Codebuild Deployment

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  AWS_ACCOUNT_ID: "277346929609"
  ECR_REPO: "bluebox"

jobs:
  Codebuild_Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
          unzip -q /tmp/awscliv2.zip -d /tmp
          sudo /tmp/aws/install --update

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "AKIAW5XVDIURMNURH4CR"
          aws-secret-access-key: "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"
          aws-region: ap-southeast-1

      - name: Set up AWS CLI for dev
        run: |
          echo "This repo is ${{ github.repository }}"
          # aws ec2 describe-instances --no-cli-pager
          # aws ec2 describe-volumes --no-cli-pager
          aws s3 ls

      - name: Stop EC2 Instance
        run: |
          # aws s3 ls  # Just a sample AWS command to check S3 buckets (can be removed or replaced)
          instance_ids=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=bluebox" --query 'Reservations[*].Instances[*].InstanceId' --output text)
          echo "All Instance IDs: $instance_ids"

          for id in $instance_ids; do
            echo "Rebooting Instance ID: $id"
            # aws ec2 reboot-instances --instance-ids $id --no-cli-pager

            # while true; do

          done

        env:
          AWS_ACCESS_KEY_ID: "AKIAW5XVDIURMHNQBBVG"
          AWS_SECRET_ACCESS_KEY: "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"
          AWS_DEFAULT_REGION: ap-southeast-1
