name: Create comment on new issues

on:
    issues:
        types:
            - opened
            - closed

jobs:
    comment-with-action:
        runs-on: ubuntu-latest
        steps:
            - name: "dump-github-issues"
              run: echo '${{ toJson(github.event) }}' | jq '.'