name: Triggering Workflow

on:
  push:
    branches:
      - test

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and other steps here
